language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install codeclimate-test-reporter coverage mock
# command to run tests
script:
  - coverage run ./test_nrpe_template.py
  - codeclimate-test-reporter || echo "Ignoring Code Climate reporter upload failure"